# require 'rails_helper'

# # This spec was generated by rspec-rails when you ran the scaffold generator.
# # It demonstrates how one might use RSpec to test the controller code that
# # was generated by Rails when you ran the scaffold generator.
# #
# # It assumes that the implementation code is generated by the rails scaffold
# # generator. If you are using any extension libraries to generate different
# # controller code, this generated spec may or may not pass.
# #
# # It only uses APIs available in rails and/or rspec-rails. There are a number
# # of tools you can use to make these specs even more expressive, but we're
# # sticking to rails and rspec-rails APIs to keep things simple and stable.

# RSpec.describe "/monthly_goals", type: :request do
  
#   # This should return the minimal set of attributes required to create a valid
#   # MonthlyGoal. As you add validations to MonthlyGoal, be sure to
#   # adjust the attributes here as well.
#   let(:valid_attributes) {
#     skip("Add a hash of attributes valid for your model")
#   }

#   let(:invalid_attributes) {
#     skip("Add a hash of attributes invalid for your model")
#   }

#   describe "GET /index" do
#     it "renders a successful response" do
#       MonthlyGoal.create! valid_attributes
#       get monthly_goals_url
#       expect(response).to be_successful
#     end
#   end

#   describe "GET /show" do
#     it "renders a successful response" do
#       monthly_goal = MonthlyGoal.create! valid_attributes
#       get monthly_goal_url(monthly_goal)
#       expect(response).to be_successful
#     end
#   end

#   describe "GET /new" do
#     it "renders a successful response" do
#       get new_monthly_goal_url
#       expect(response).to be_successful
#     end
#   end

#   describe "GET /edit" do
#     it "renders a successful response" do
#       monthly_goal = MonthlyGoal.create! valid_attributes
#       get edit_monthly_goal_url(monthly_goal)
#       expect(response).to be_successful
#     end
#   end

#   describe "POST /create" do
#     context "with valid parameters" do
#       it "creates a new MonthlyGoal" do
#         expect {
#           post monthly_goals_url, params: { monthly_goal: valid_attributes }
#         }.to change(MonthlyGoal, :count).by(1)
#       end

#       it "redirects to the created monthly_goal" do
#         post monthly_goals_url, params: { monthly_goal: valid_attributes }
#         expect(response).to redirect_to(monthly_goal_url(MonthlyGoal.last))
#       end
#     end
  

#     context "with invalid parameters" do
#       it "does not create a new MonthlyGoal" do
#         expect {
#           post monthly_goals_url, params: { monthly_goal: invalid_attributes }
#         }.to change(MonthlyGoal, :count).by(0)
#       end

    
#       it "renders a successful response (i.e. to display the 'new' template)" do
#         post monthly_goals_url, params: { monthly_goal: invalid_attributes }
#         expect(response).to be_successful
#       end
#     end 
#     end


#   describe "PATCH /update" do
#     context "with valid parameters" do
#       let(:new_attributes) {
#         skip("Add a hash of attributes valid for your model")
#       }

#       it "updates the requested monthly_goal" do
#         monthly_goal = MonthlyGoal.create! valid_attributes
#         patch monthly_goal_url(monthly_goal), params: { monthly_goal: new_attributes }
#         monthly_goal.reload
#         skip("Add assertions for updated state")
#       end

#       it "redirects to the monthly_goal" do
#         monthly_goal = MonthlyGoal.create! valid_attributes
#         patch monthly_goal_url(monthly_goal), params: { monthly_goal: new_attributes }
#         monthly_goal.reload
#         expect(response).to redirect_to(monthly_goal_url(monthly_goal))
#       end
#     end

#     context "with invalid parameters" do
    
#       it "renders a successful response (i.e. to display the 'edit' template)" do
#         monthly_goal = MonthlyGoal.create! valid_attributes
#         patch monthly_goal_url(monthly_goal), params: { monthly_goal: invalid_attributes }
#         expect(response).to be_successful
#       end
#     end
#   end
  

#   describe "DELETE /destroy" do
#     it "destroys the requested monthly_goal" do
#       monthly_goal = MonthlyGoal.create! valid_attributes
#       expect {
#         delete monthly_goal_url(monthly_goal)
#       }.to change(MonthlyGoal, :count).by(-1)
#     end

#     it "redirects to the monthly_goals list" do
#       monthly_goal = MonthlyGoal.create! valid_attributes
#       delete monthly_goal_url(monthly_goal)
#       expect(response).to redirect_to(monthly_goals_url)
#     end
#   end
# end 
