require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/weekly_goals", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # WeeklyGoal. As you add validations to WeeklyGoal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WeeklyGoal.create! valid_attributes
      get weekly_goals_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      weekly_goal = WeeklyGoal.create! valid_attributes
      get weekly_goal_url(weekly_goal)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_weekly_goal_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      weekly_goal = WeeklyGoal.create! valid_attributes
      get edit_weekly_goal_url(weekly_goal)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WeeklyGoal" do
        expect {
          post weekly_goals_url, params: { weekly_goal: valid_attributes }
        }.to change(WeeklyGoal, :count).by(1)
      end

      it "redirects to the created weekly_goal" do
        post weekly_goals_url, params: { weekly_goal: valid_attributes }
        expect(response).to redirect_to(weekly_goal_url(WeeklyGoal.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WeeklyGoal" do
        expect {
          post weekly_goals_url, params: { weekly_goal: invalid_attributes }
        }.to change(WeeklyGoal, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post weekly_goals_url, params: { weekly_goal: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested weekly_goal" do
        weekly_goal = WeeklyGoal.create! valid_attributes
        patch weekly_goal_url(weekly_goal), params: { weekly_goal: new_attributes }
        weekly_goal.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the weekly_goal" do
        weekly_goal = WeeklyGoal.create! valid_attributes
        patch weekly_goal_url(weekly_goal), params: { weekly_goal: new_attributes }
        weekly_goal.reload
        expect(response).to redirect_to(weekly_goal_url(weekly_goal))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        weekly_goal = WeeklyGoal.create! valid_attributes
        patch weekly_goal_url(weekly_goal), params: { weekly_goal: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested weekly_goal" do
      weekly_goal = WeeklyGoal.create! valid_attributes
      expect {
        delete weekly_goal_url(weekly_goal)
      }.to change(WeeklyGoal, :count).by(-1)
    end

    it "redirects to the weekly_goals list" do
      weekly_goal = WeeklyGoal.create! valid_attributes
      delete weekly_goal_url(weekly_goal)
      expect(response).to redirect_to(weekly_goals_url)
    end
  end
end
